package com.hiber;
// Generated Apr 28, 2014 12:48:14 AM by Hibernate Tools 3.6.0



/**
 * Venues generated by hbm2java
 */
public class Venues  implements java.io.Serializable {


     private int venueid;
     private String latitude;
     private String longitude;

    @Override
    public String toString() {
        return "Venues{" + "venueid=" + venueid + ", latitude=" + latitude + ", longitude=" + longitude + '}';
    }

    public void setVenueid(int venueid) {
        this.venueid = venueid;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public int getVenueid() {
        return venueid;
    }

    public String getLatitude() {
        return latitude;
    }

    public String getLongitude() {
        return longitude;
    }
}


